<h1>Entrega 3 - Equipo Morado - XGBClassifier<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#1)-Incluir-en-forma-resumida-la-información-de-las-variables-relevantes." data-toc-modified-id="1)-Incluir-en-forma-resumida-la-información-de-las-variables-relevantes.-1">1) Incluir en forma resumida la información de las variables relevantes.</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#1.-Muestren-la-información-general-del-set-de-datos-a-utilizar-para-la-fase-de-modelación-de-datos.-Incluir-un-resumen-con-la-descripción-de-las-variables-relevantes-para-el-análisis." data-toc-modified-id="1.-Muestren-la-información-general-del-set-de-datos-a-utilizar-para-la-fase-de-modelación-de-datos.-Incluir-un-resumen-con-la-descripción-de-las-variables-relevantes-para-el-análisis.-1.0.1">1. Muestren la información general del set de datos a utilizar para la fase de modelación de datos. Incluir un resumen con la descripción de las variables relevantes para el análisis.</a></span></li><li><span><a href="#3.-Definan-la-variable-target,-o-de-respuesta-(dependiente)-y-las-features-o-variables-predictoras-(independientes)" data-toc-modified-id="3.-Definan-la-variable-target,-o-de-respuesta-(dependiente)-y-las-features-o-variables-predictoras-(independientes)-1.0.2">3. Definan la variable target, o de respuesta (dependiente) y las features o variables predictoras (independientes)</a></span></li><li><span><a href="#4.-Definan-qué-tipos-de-modelos-debes-utilizar,-de-regresión-o-de-clasificación.-Justificar-su-respuesta." data-toc-modified-id="4.-Definan-qué-tipos-de-modelos-debes-utilizar,-de-regresión-o-de-clasificación.-Justificar-su-respuesta.-1.0.3">4. Definan qué tipos de modelos debes utilizar, de regresión o de clasificación. Justificar su respuesta.</a></span></li><li><span><a href="#5.-Definan-el-dataset-para-entrenamiento-y-prueba." data-toc-modified-id="5.-Definan-el-dataset-para-entrenamiento-y-prueba.-1.0.4">5. Definan el dataset para entrenamiento y prueba.</a></span></li><li><span><a href="#6.-Realizar-varias-veces-los-siguientes-pasos,-para-tratar-de-encontrar-el-mejor-modelo-de-predicción:" data-toc-modified-id="6.-Realizar-varias-veces-los-siguientes-pasos,-para-tratar-de-encontrar-el-mejor-modelo-de-predicción:-1.0.5">6. Realizar varias veces los siguientes pasos, para tratar de encontrar el mejor modelo de predicción:</a></span><ul class="toc-item"><li><span><a href="#a)-Prueben-todos-los-modelos-de-clasificación-vistos-en-clase-para-generar-predicciones.-Al-utilizar-árboles-de-decisión,-genera-también-la-imagen-del-mismo." data-toc-modified-id="a)-Prueben-todos-los-modelos-de-clasificación-vistos-en-clase-para-generar-predicciones.-Al-utilizar-árboles-de-decisión,-genera-también-la-imagen-del-mismo.-1.0.5.1">a) Prueben todos los modelos de clasificación vistos en clase para generar predicciones. Al utilizar árboles de decisión, genera también la imagen del mismo.</a></span></li><li><span><a href="#b)-Calculen-y-utilicen-métricas-para-comparar-los-modelos:-accuracy,-matriz-de-confusión,-precisión,-sensitividad,-especificidad." data-toc-modified-id="b)-Calculen-y-utilicen-métricas-para-comparar-los-modelos:-accuracy,-matriz-de-confusión,-precisión,-sensitividad,-especificidad.-1.0.5.2">b) Calculen y utilicen métricas para comparar los modelos: accuracy, matriz de confusión, precisión, sensitividad, especificidad.</a></span></li><li><span><a href="#c)-Implementen-hiperparámetros" data-toc-modified-id="c)-Implementen-hiperparámetros-1.0.5.3">c) Implementen hiperparámetros</a></span></li><li><span><a href="#d)-Implementen-procedimiento-de-validación-cruzada-para-sus-modelos" data-toc-modified-id="d)-Implementen-procedimiento-de-validación-cruzada-para-sus-modelos-1.0.5.4">d) Implementen procedimiento de validación cruzada para sus modelos</a></span></li></ul></li><li><span><a href="#7.-Describan-el-proceso-realizado-y-presenten-sus-conclusiones-al-respecto" data-toc-modified-id="7.-Describan-el-proceso-realizado-y-presenten-sus-conclusiones-al-respecto-1.0.6">7. Describan el proceso realizado y presenten sus conclusiones al respecto</a></span></li></ul></li></ul></li><li><span><a href="#4)-Análisis-de-resultados-y-selección-de-modelo-de-predicción." data-toc-modified-id="4)-Análisis-de-resultados-y-selección-de-modelo-de-predicción.-2">4) Análisis de resultados y selección de modelo de predicción.</a></span></li><li><span><a href="#6)-Agregar-Conclusiones." data-toc-modified-id="6)-Agregar-Conclusiones.-3">6) Agregar Conclusiones.</a></span></li><li><span><a href="#7)-Actualizar-el-documento-rector-con-los-hallazgos-de-esta-etapa." data-toc-modified-id="7)-Actualizar-el-documento-rector-con-los-hallazgos-de-esta-etapa.-4">7) Actualizar el documento rector con los hallazgos de esta etapa.</a></span></li></ul></div>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.model_selection import train_test_split,cross_val_score, GridSearchCV, KFold, StratifiedKFold, RandomizedSearchCV
from xgboost import XGBClassifier
from sklearn.metrics import precision_score, recall_score, accuracy_score, classification_report
import pickle
import seaborn as sns
from mpl_toolkits.mplot3d import Axes3D
from sklearn.preprocessing import OneHotEncoder
from sklearn.utils import shuffle
from sklearn import model_selection
from sklearn.metrics import confusion_matrix
import tensorflow as tf
from tensorflow import keras
from keras import layers
import tensorflow_docs as tfdocs
import tensorflow_docs.plots
import tensorflow_docs.modeling
import keras
from keras.layers import Dense, Dropout, Activation, Flatten, Conv1D, Conv2D, MaxPooling1D, MaxPooling2D, Lambda, MaxPool2D, BatchNormalization
from keras.utils import np_utils
from keras import models, layers, optimizers
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.utils import class_weight
from tensorflow import keras
from tensorflow.keras.optimizers import Adam
from keras.models import Sequential, model_from_json
from keras.preprocessing.image import ImageDataGenerator
from keras.callbacks import ReduceLROnPlateau, ModelCheckpoint
from keras import backend as K
from keras.applications.vgg16 import VGG16
from keras.models import Model

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, label_ranking_average_precision_score, label_ranking_loss, coverage_error 
import itertools

import warnings
warnings.filterwarnings("ignore")

2022-11-17 14:34:11.176850: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
db = pd.read_csv("InfraccionesGDL_DB_v1.csv")
db['INFRACCIONES'] = db[['INFRACCION_1.0',
       'INFRACCION_4.0', 'INFRACCION_5.0']].sum(axis = 1)

db = db.loc[db['INFRACCIONES'] > 0]

db['INFRACCION'] = 0
condition_1 = (db['INFRACCION_1.0'] == 1)
db.loc[condition_1, 'INFRACCION'] = 1

condition_4 = (db['INFRACCION_4.0'] == 1)
db.loc[condition_4, 'INFRACCION'] = 4

condition_5 = (db['INFRACCION_5.0'] == 1)
db.loc[condition_5, 'INFRACCION'] = 5

db = db.drop(columns = ["Unnamed: 0"])

db = db[['ESTADO', 'MARCA', 'CALLE', 'CRUCE', 'FECHA', 'MES', 'ANO',
         'HORA', 'HORA_NUM', 'LATITUD', 'LONGITUD', 'INFRACCION']]

db.FECHA = pd.to_datetime(db.FECHA)

db.HORA = pd.to_datetime(db.HORA)
db.HORA = [time.time() for time in db.HORA]

db.DIAS = db.FECHA.dt.weekday

In [3]:
db.ESTADO.unique()

array(['morelos', 'jalisco', 'estado de mexico', 'sinaloa',
       'baja california norte', 'san luis potosi', 'nayarit',
       'ciudad de mexico', 'yucatan', 'guerrero', 'sonora', 'michoacan',
       'durango', 'chihuahua', 'colima', 'quintana roo', 'queretaro',
       'guanajuato', 'baja california sur', 'nuevo leon', 'hidalgo',
       'oaxaca', 'puebla', 'tabasco', 'aguascalientes', 'zacatecas',
       'tamaulipas', 'campeche', 'coahuila', 'veracruz', 'tlaxcala',
       'chiapas', 'extranjero'], dtype=object)

In [4]:
db.columns

Index(['ESTADO', 'MARCA', 'CALLE', 'CRUCE', 'FECHA', 'MES', 'ANO', 'HORA',
       'HORA_NUM', 'LATITUD', 'LONGITUD', 'INFRACCION'],
      dtype='object')

In [5]:
db.head(5)[2:]

ESTADO         MARCA                 CALLE                 CRUCE  \
2  jalisco    volkswagen     avenida de la paz  francisco de quevedo   
3  jalisco  freightliner     avenida de la paz  francisco de quevedo   
4  jalisco    volkswagen  francisco de quevedo     avenida de la paz   

       FECHA     MES   ANO      HORA  HORA_NUM  LATITUD  LONGITUD  INFRACCION  
2 2021-08-16  August  2021  11:26:00        11    20.67   -103.38           1  
3 2021-08-16  August  2021  11:27:00        11    20.67   -103.38           5  
4 2021-08-16  August  2021  11:38:00        11    20.67   -103.38           1

### 1) Incluir en forma resumida la información de las variables relevantes.

In [6]:
db.describe(include = 'all')

ESTADO   MARCA              CALLE          CRUCE  \
count    305801  305801             305765         305716   
unique       33      67               6687           9774   
top     jalisco  nissan  avenida de la paz  lópez cotilla   
freq     229601   45311              11433           7608   
first       NaN     NaN                NaN            NaN   
last        NaN     NaN                NaN            NaN   
mean        NaN     NaN                NaN            NaN   
std         NaN     NaN                NaN            NaN   
min         NaN     NaN                NaN            NaN   
25%         NaN     NaN                NaN            NaN   
50%         NaN     NaN                NaN            NaN   
75%         NaN     NaN                NaN            NaN   
max         NaN     NaN                NaN            NaN   

                      FECHA     MES            ANO      HORA       HORA_NUM  \
count                305801  305801  305801.000000    305801  305801.000000   
unique                  643      12            NaN      2210            NaN   
top     2021-02-17 00:00:00   March            NaN  12:14:00            NaN   
freq                   1251   32912            NaN       504            NaN   
first   2021-01-02 00:00:00     NaN            NaN       NaN            NaN   
last    2022-12-10 00:00:00     NaN            NaN       NaN            NaN   
mean                    NaN     NaN    2021.551228       NaN       9.755916   
std                     NaN     NaN       0.497370       NaN       6.885302   
min                     NaN     NaN    2021.000000       NaN       0.000000   
25%                     NaN     NaN    2021.000000       NaN       0.000000   
50%                     NaN     NaN    2022.000000       NaN      12.000000   
75%                     NaN     NaN    2022.000000       NaN      15.000000   
max                     NaN     NaN    2022.000000       NaN      23.000000   

              LATITUD       LONGITUD     INFRACCION  
count   305791.000000  305791.000000  305801.000000  
unique            NaN            NaN            NaN  
top               NaN            NaN            NaN  
freq              NaN            NaN            NaN  
first             NaN            NaN            NaN  
last              NaN            NaN            NaN  
mean        20.676389    -103.360824       2.757996  
std          0.039252       0.034785       1.747697  
min         19.910670    -110.957672       1.000000  
25%         20.671469    -103.371738       1.000000  
50%         20.674378    -103.361184       4.000000  
75%         20.677945    -103.349153       4.000000  
max         31.326010    -102.445630       5.000000

##### 1. Muestren la información general del set de datos a utilizar para la fase de modelación de datos. Incluir un resumen con la descripción de las variables relevantes para el análisis.

<span style="color:purple;font-size:18px">

1. **ESTADO**: Estado de la placa del automóvil infraccionado | *Tipo String.*
2. **MARCA**: Marca del automóvil infraccionado | *Tipo String.*
3. **CALLE**: Calle principal donde se realizó la infracción | *Tipo String.*
4. **CRUCE**: Cruce más cercano de la calle principal donde se realizó la infracción | *Tipo String.*
5. **FECHA**: Fecha de la infracción | *Tipo Datetime.*
6. **MES**: Mes (en inglés) de la infracción | *Tipo int: Valores del 1 al 12.*
7. **HORA_NUM**: Hora de la infracción | *Tipo Datetime.*
8. **LATITUD**: Latitud geográfica de la infracción | *Tipo int.*
9. **LONGITUD**: Longitud geográfica de la infracción | *Tipo int.* 
10. **INFRACCIÓN**: Tipo de infracción cometida por el vehículo | *Tipo int. Valores 1, 4 o 5. </span>

##### 3. Definan la variable target, o de respuesta (dependiente) y las features o variables predictoras (independientes)

In [7]:
target = ["INFRACCION"] 

features = ['ESTADO', 'MARCA', 'CALLE', 'CRUCE', 'FECHA', 'MES', 'HORA_NUM', 'LATITUD', 'LONGITUD']

<span style="color:purple;font-size:18px"> Nuestro target será el tipo de **INFRACCIÓN**, donde los features serán: **ESTADO, MARCA, CALLE, CRUCE, FECHA, MES, HORA_NUM, LATITUD, LONGITUD**. </span>

##### 4. Definan qué tipos de modelos debes utilizar, de regresión o de clasificación. Justificar su respuesta.

<span style="color:purple;font-size:18px"> El modelo a utilizar será un **MODELO DE CLASIFICACIÓN MULTIVARIABLE** para definir el tipo de infracción. </span>

##### 5. Definan el dataset para entrenamiento y prueba.


In [8]:
clean_training = db.loc[db['ANO'] == 2021]
clean_prediction = db.loc[db['ANO'] == 2022]

clean_prediction_notarget = clean_prediction[features]

<span style="color:purple;font-size:18px">El training serán las infracciones de 2021 y la predicción las infracciones de 2022. </span>

In [9]:
clean_training.columns

Index(['ESTADO', 'MARCA', 'CALLE', 'CRUCE', 'FECHA', 'MES', 'ANO', 'HORA',
       'HORA_NUM', 'LATITUD', 'LONGITUD', 'INFRACCION'],
      dtype='object')

##### 6. Realizar varias veces los siguientes pasos, para tratar de encontrar el mejor modelo de predicción:

###### a) Prueben todos los modelos de clasificación vistos en clase para generar predicciones. Al utilizar árboles de decisión, genera también la imagen del mismo.

In [10]:
clean_training = clean_training.dropna(subset = 'LATITUD')

x_oa = clean_training.drop(['INFRACCION'], axis=1)

str_features = ['ESTADO', 'MARCA']

for i in range(len(str_features)):
    clean_training[str_features[i]] = clean_training[str_features[i]].astype("category")
    clean_training[str_features[i]+"_cat"] = clean_training[str_features[i]].cat.reorder_categories(clean_training[str_features[i]].unique(),
                                                                       ordered=True)
    clean_training[str_features[i]+"_cat"] = clean_training[str_features[i]+"_cat"].cat.codes

x_oa['MES'] = x_oa.FECHA.dt.month

for i in range(len(str_features)):
    x_oa[str_features[i]] = x_oa[str_features[i]].astype("category")
    x_oa[str_features[i]+"_cat"] = x_oa[str_features[i]].cat.reorder_categories(x_oa[str_features[i]].unique(),
                                                                       ordered=True)
    x_oa[str_features[i]+"_cat"] = x_oa[str_features[i]+"_cat"].cat.codes

x_oa['MES'] = x_oa.FECHA.dt.month

x_oa_all = x_oa

In [21]:
x_oa_all.head(3)

ESTADO       MARCA                       CALLE                 CRUCE  \
0  morelos        jeep  calle manuel lópez cotilla  francisco de quevedo   
1  jalisco       kicks          calle lope de vega     avenida de la paz   
2  jalisco  volkswagen           avenida de la paz  francisco de quevedo   

       FECHA  MES   ANO      HORA  HORA_NUM  LATITUD  LONGITUD  ESTADO_cat  \
0 2021-08-16    8  2021  11:11:00        11    20.67   -103.38          17   
1 2021-08-16    8  2021  11:22:00        11    20.67   -103.38          15   
2 2021-08-16    8  2021  11:26:00        11    20.67   -103.38          15   

   MARCA_cat  
0         30  
1         33  
2         64

3. Gradient Boost

In [11]:
x_oa = x_oa_all[['ESTADO_cat', 'MARCA_cat', 'MES', 'HORA_NUM', 'LATITUD', 'LONGITUD']]
y_oa = clean_training['INFRACCION']
y_oa = y_oa.replace({1: 0, 4: 1, 5: 2})

xtrain_oa, xtest_oa, ytrain_oa, ytest_oa = train_test_split(x_oa, y_oa, test_size=0.25, random_state=1)

In [12]:
gradient_boosting_cls_oa = XGBClassifier(
    n_estimators=4000,
    learning_rate=0.01,
    max_depth=6)

gradient_boosting_cls_oa.fit(xtrain_oa, ytrain_oa)

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
              importance_type=None, interaction_constraints='',
              learning_rate=0.01, max_bin=256, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=4000,
              n_jobs=0, num_parallel_tree=1, objective='multi:softprob',
              predictor='auto', random_state=0, reg_alpha=0, ...)

In [13]:
predictions_grad_oa = gradient_boosting_cls_oa.predict(xtest_oa)

###### b) Calculen y utilicen métricas para comparar los modelos: accuracy, matriz de confusión, precisión, sensitividad, especificidad.

3. Gradient Boost

In [18]:
print(f"Accuracy on test set:{round(gradient_boosting_cls_oa.score(xtest_oa, ytest_oa),2)}")

print(classification_report(ytest_oa, predictions_grad_oa))

cm_oa = confusion_matrix(ytest_oa, predictions_grad_oa)
print('Confusion matrix\n\n', cm_oa)

Accuracy on test set:0.84
              precision    recall  f1-score   support

           0       0.87      0.97      0.92     15373
           1       0.82      0.78      0.80     10576
           2       0.79      0.67      0.73      8358

    accuracy                           0.84     34307
   macro avg       0.83      0.81      0.81     34307
weighted avg       0.84      0.84      0.84     34307

Confusion matrix

 [[14962   224   187]
 [ 1043  8234  1299]
 [ 1143  1610  5605]]


###### c) Implementen hiperparámetros

In [15]:
from pprint import pprint
pprint(gradient_boosting_cls_oa.get_params())

{'base_score': 0.5,
 'booster': 'gbtree',
 'callbacks': None,
 'colsample_bylevel': 1,
 'colsample_bynode': 1,
 'colsample_bytree': 1,
 'early_stopping_rounds': None,
 'enable_categorical': False,
 'eval_metric': None,
 'gamma': 0,
 'gpu_id': -1,
 'grow_policy': 'depthwise',
 'importance_type': None,
 'interaction_constraints': '',
 'learning_rate': 0.01,
 'max_bin': 256,
 'max_cat_to_onehot': 4,
 'max_delta_step': 0,
 'max_depth': 6,
 'max_leaves': 0,
 'min_child_weight': 1,
 'missing': nan,
 'monotone_constraints': '()',
 'n_estimators': 4000,
 'n_jobs': 0,
 'num_parallel_tree': 1,
 'objective': 'multi:softprob',
 'predictor': 'auto',
 'random_state': 0,
 'reg_alpha': 0,
 'reg_lambda': 1,
 'sampling_method': 'uniform',
 'scale_pos_weight': None,
 'subsample': 1,
 'tree_method': 'exact',
 'use_label_encoder': False,
 'validate_parameters': 1,
 'verbosity': None}


In [16]:
param_grid = {'n_estimators': [1000, 1500, 2000, 2500, 3000, 4000],
              'max_depth': [5, 6, 7, 8, 9],
              'n_jobs': [0, 1, 2, 3]}

In [22]:
gradient_boosting_cls_oa_hyper = RandomizedSearchCV(gradient_boosting_cls_oa, param_grid, cv = 5)
gradient_boosting_cls_oa_hyper.fit(xtest_oa, ytest_oa)

RandomizedSearchCV(cv=5,
                   estimator=XGBClassifier(base_score=0.5, booster='gbtree',
                                           callbacks=None, colsample_bylevel=1,
                                           colsample_bynode=1,
                                           colsample_bytree=1,
                                           early_stopping_rounds=None,
                                           enable_categorical=False,
                                           eval_metric=None, gamma=0, gpu_id=-1,
                                           grow_policy='depthwise',
                                           importance_type=None,
                                           interaction_constraints='',
                                           learning_rate=0.01, max_bin=256,
                                           max_cat...
                                           max_leaves=0, min_child_weight=1,
                                           missing=nan,
                                           monotone_constraints='()',
                                           n_estimators=4000, n_jobs=0,
                                           num_parallel_tree=1,
                                           objective='multi:softprob',
                                           predictor='auto', random_state=0,
                                           reg_alpha=0, ...),
                   param_distributions={'learning_rate': [0.001, 0.01, 0.1],
                                        'max_depth': [3, 4, 5, 6, 7, 8],
                                        'n_estimators': [1000, 1500, 2000, 2500,
                                                         3000, 4000, 50000,
                                                         6000],
                                        'n_jobs': [0, 1, 2, 3]})

In [33]:
gradient_boosting_cls_oa.get_params

<bound method XGBModel.get_params of XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
              importance_type=None, interaction_constraints='',
              learning_rate=0.01, max_bin=256, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=4000,
              n_jobs=0, num_parallel_tree=1, objective='multi:softprob',
              predictor='auto', random_state=0, reg_alpha=0, ...)>

In [23]:
print("The best parameters across ALL searched params:\n", gradient_boosting_cls_oa_hyper.best_params_)

The best parameters across ALL searched params:
 {'n_jobs': 2, 'n_estimators': 3000, 'max_depth': 8, 'learning_rate': 0.01}


In [24]:
gradient_boosting_cls_oa_best = XGBClassifier(gradient_boosting_cls_oa_hyper.best_params_)

gradient_boosting_cls_oa_best.fit(xtrain_oa, ytrain_oa)

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
              importance_type=None, interaction_constraints='',
              learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=0, num_parallel_tree=1, objective='multi:softprob',
              predictor='auto', random_state=0, reg_alpha=0, ...)

In [25]:
predictions_grad_oa_best = gradient_boosting_cls_oa_best.predict(xtest_oa)

In [27]:
print(f"Accuracy on test set:{round(gradient_boosting_cls_oa_best.score(xtest_oa, ytest_oa),2)}")

print(classification_report(ytest_oa, predictions_grad_oa_best))

Accuracy on test set:0.84
              precision    recall  f1-score   support

           0       0.87      0.97      0.92     15373
           1       0.82      0.78      0.80     10576
           2       0.79      0.67      0.72      8358

    accuracy                           0.84     34307
   macro avg       0.83      0.81      0.81     34307
weighted avg       0.83      0.84      0.83     34307



In [38]:
cm_oa_best = confusion_matrix(ytest_oa, predictions_grad_oa_best)
print('Confusion matrix\n\n', cm_oa_best)

Confusion matrix

 [[14969   220   184]
 [ 1067  8204  1305]
 [ 1193  1580  5585]]


###### d) Implementen procedimiento de validación cruzada para sus modelos

In [28]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

cv = KFold(n_splits=5, random_state=0, shuffle=True)

for train_index, val_index in cv.split(xtrain_oa):
        print("TEST: ",val_index[:10],"TRAIN: ",train_index[:10]) 
        train, Xval = xtrain_oa.iloc[train_index], xtrain_oa.iloc[val_index]
        ytrain, yval = ytrain_oa.iloc[train_index], ytrain_oa.iloc[val_index]
        print((ytrain==1).sum(),(ytrain==0).sum(),(yval==1).sum(),(yval==0).sum())

TEST:  [ 3  6  9 14 17 23 25 26 34 36] TRAIN:  [ 0  1  2  4  5  7  8 10 11 12]
25331 36855 6160 9257
TEST:  [ 1  8 11 12 15 18 22 24 28 29] TRAIN:  [ 0  2  3  4  5  6  7  9 10 13]
25154 36908 6337 9204
TEST:  [ 0  4  5 32 39 44 45 47 58 64] TRAIN:  [ 1  2  3  6  7  8  9 10 11 12]
25233 36783 6258 9329
TEST:  [ 7 16 19 31 33 35 37 40 53 59] TRAIN:  [ 0  1  2  3  4  5  6  8  9 10]
25124 36906 6367 9206
TEST:  [ 2 10 13 20 21 27 30 43 46 55] TRAIN:  [ 0  1  3  4  5  6  7  8  9 11]
25122 36996 6369 9116


In [34]:
scores_val_oa = cross_val_score(gradient_boosting_cls_oa, xtrain_oa, ytrain_oa, cv=5)
scores_val_oa

array([0.83807812, 0.83560047, 0.84371356, 0.83933343, 0.84292863])

In [35]:
print("Accuracy: %0.2f" % (scores_val_oa.mean()))

Accuracy: 0.84


##### 7. Describan el proceso realizado y presenten sus conclusiones al respecto

<span style="color:purple;font-size:18px"> 
    

3. Gradient XBoost classifier: El mejor modelo que se adaptó a los pocos datos que se tienen. Este modelo produce un modelo predictivo en forma de un conjunto de modelos de predicción débiles, típicamente árboles de decisión. En cada iteración, los árboles de decisión aprenden a determinar los errores residuales (obtenidos por el gradiente negativo) por lo que se le da un peso mayor a las observaciones difíciles de clasificar.

</span>

### 4) Análisis de resultados y selección de modelo de predicción.

In [36]:
x_oa_all[str_features + [str_features[i] + "_cat" for i in range(0, len(str_features))]].head(3)

ESTADO       MARCA  ESTADO_cat  MARCA_cat
0  morelos        jeep          17         30
1  jalisco       kicks          15         33
2  jalisco  volkswagen          15         64

In [39]:
# Guardar dos diccionarios con los valores reordenados a categorías

estados_dict = pd.pivot_table(x_oa_all, index = 'ESTADO')['ESTADO_cat'].to_dict()
marcas_dict = pd.pivot_table(x_oa_all, index = 'MARCA')['MARCA_cat'].to_dict()

In [40]:
estados_dict

{'aguascalientes': 0,
 'baja california norte': 1,
 'baja california sur': 2,
 'campeche': 3,
 'chiapas': 4,
 'chihuahua': 5,
 'ciudad de mexico': 6,
 'coahuila': 7,
 'colima': 8,
 'durango': 9,
 'estado de mexico': 10,
 'extranjero': 11,
 'guanajuato': 12,
 'guerrero': 13,
 'hidalgo': 14,
 'jalisco': 15,
 'michoacan': 16,
 'morelos': 17,
 'nayarit': 18,
 'nuevo leon': 19,
 'oaxaca': 20,
 'puebla': 21,
 'queretaro': 22,
 'quintana roo': 23,
 'san luis potosi': 24,
 'sinaloa': 25,
 'sonora': 26,
 'tabasco': 27,
 'tamaulipas': 28,
 'tlaxcala': 29,
 'veracruz': 30,
 'yucatan': 31,
 'zacatecas': 32}

In [46]:
feature_importance = pd.DataFrame(index = xtrain_oa.columns.tolist()).reset_index()
feature_importance.columns = ['features']
feature_importance['importance'] = np.round(gradient_boosting_cls_oa.feature_importances_ * 100, 1)
feature_importance['importance'] = np.round(feature_importance['importance'], 0)

fig = px.bar(feature_importance, x = "features", y = "importance",
             title="Gradient XBoost Feature Importance",
             color_discrete_sequence=px.colors.qualitative.Prism, text = 'importance')
fig.show()

In [55]:
clean_prediction_notarget['MES'] = clean_prediction_notarget.FECHA.dt.month

clean_prediction_notarget['ESTADO_cat'] = clean_prediction_notarget['ESTADO'].replace(estados_dict)
clean_prediction_notarget['MARCA_cat'] = clean_prediction_notarget['MARCA'].replace(marcas_dict)

clean_pred_target = clean_prediction['INFRACCION'].replace({1: 0, 4: 1, 5: 2})
clean_pred_target = clean_pred_target.tolist()

clean_prediction_notarget = clean_prediction_notarget[x_oa.columns]

In [56]:
predictions_grad_2022_oa = gradient_boosting_cls_oa.predict(clean_prediction_notarget)

In [57]:
import plotly.figure_factory as ff

cnf_matrix = confusion_matrix(clean_pred_target, predictions_grad_2022_oa)
cnf_matrix = cnf_matrix.astype('float') / cnf_matrix.sum(axis=1)[:, np.newaxis]
cnf_matrix = np.round(cnf_matrix, 2)

x_cm, y_cm = ['Tipo 1', 'Tipo 4', 'Tipo 5'], ['Tipo 1', 'Tipo 4', 'Tipo 5']
z_text = [[str(y_cm) for y_cm in x_cm] for x_cm in cnf_matrix]

fig = ff.create_annotated_heatmap(cnf_matrix, x = x_cm, y = y_cm,
                                  annotation_text = z_text, colorscale='purples')

# add title
fig.update_layout(title_text='<i><b>2022 Confusion matrix: XGBClassifier</b></i>')

fig.add_annotation(dict(font=dict(color="black",size=14),
                        x=0.5, y=-0.15, showarrow=False, text="Predicted value",
                        xref="paper",  yref="paper"))

fig.add_annotation(dict(font=dict(color="black",size=14),
                        x=-0.35, y=0.5, showarrow=False, text="Real value", textangle=-90,
                        xref="paper", yref="paper"))

fig.update_layout(margin=dict(t=50, l=200))

fig['data'][0]['showscale'] = False
fig.show()

### 6) Agregar Conclusiones.


<span style="color:purple;font-size:18px"> 
    
Se tomó el modelo *Gradient XBoost*, que tiene el mejor accuracy de todos, para realizar la predicción del tipo de infracción que se cometerá en 2022, donde vemos que el accuracy general de dicha predicción fue de 77% tomando en cuenta las tres tipos de infracciones que se pueden cometer. 
    
La ZMG recibe alrededor de 1,000 infraccionesd al día, de las cuales solo alrededor del 10% son pagadas en cada año. Este modelo está enfocado en dos principales metas: Una para el ciudadano conductor, donde a partir del Estado de su placa, Modelo de su carro, mes y hora donde se estacionará, y latitud y longitud del lugar; a partir de esto, se podrá hacer una valoración si entra en perfil estadístico de infracciones en la ciudad y esteriotipos de conductores que el modelo aprendió. Por otro lado, beneficiará a la Entidad Pública, ya que a partir de este modelo se puede tener una proyección más certera, basada en histórico, sobre las infracciones a futuro. A partir de estas predicciones, se pueden crear o proponer políticas públicas o programas sociales que incentiven una mejor cultura vial en la ciudad.

Apartir del análisis de estos datos podemos determinar cuáles serían las zonas más eficientes dónde agregar cajones de estacionamiento parkimovil o estacionamientos públicos.

#LaCalleEsDeTodos
</span>

In [58]:
print("https://infraccionesgdl.herokuapp.com")

https://infraccionesgdl.herokuapp.com


### 7) Actualizar el documento rector con los hallazgos de esta etapa.